# hyprtoolkit: hyprlauncher(앱 검색) 등 Hypr 앱의 테마. Catppuccin Mocha

background       = 0xff1e1e2e
base             = 0xff181825
alternate_base   = 0xff313244
text             = 0xffcdd6f4
bright_text      = 0xfff5e0dc
accent           = 0xffcba6f7
accent_secondary = 0xff89b4fa

icon_theme     = Papirus-Dark
rounding_large = 12
rounding_small = 8
